import turtle

food_list = []
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-360, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-330, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-300, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-270, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-240, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-210, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-180, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-150, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-120, -300)
food = turtle.Turtle()
food.shape("circle")
food.penup()
food.goto(-90, -300)